openapi: 3.0.0
servers:
  - url: https://spocs.getpocket.com
info:
  description: >-
    APIs to interact with sponsored content ("spocs") for Firefox, while
    preserving privacy.
  version: '2.1'
  title: Firefox Spocs
  contact:
    email: mathijs@getpocket.com
paths:
  /spocs:
    $ref: paths/spocs.yml
  /user:
    $ref: paths/user.yml
